### ISSUE TITLE
依存関係資料

### ISSUE THREAD

**Issue by Kurikara-dev** [Kurikara-dev/Finegra#43]
# 依存関係管理YAML テンプレート集

## 基本テンプレート

```yaml
# dependencies.yaml - プロジェクトルートに配置
meta:
  project_name: "your-project-name"
  version: "1.0.0"
  last_updated: "2025-06-27"
  maintainer: "team-name"

# ======= サービス依存関係 =======
services:
  - name: "user-service"
    type: "microservice"
    dependencies:
      databases:
        - name: "user-db"
          type: "postgresql"
          relationship: "owns"
          impact_if_unavailable: "high"
          notes: "ユーザー認証停止、新規登録不可"
      
      internal_services:
        - name: "notification-service"
          relationship: "publishes_to"
          impact_if_unavailable: "medium"
          events: ["user.created", "user.updated", "user.deleted"]
          notes: "通知送信失敗、ユーザー体験低下"
      
      external_apis:
        - name: "stripe-api"
          relationship: "calls"
          impact_if_unavailable: "high"
          fallback: "queue for retry"
          notes: "決済処理停止、売上直接影響"

# ======= データベース依存関係 =======
databases:
  - name: "user-db"
    type: "postgresql"
    version: "15.3"
    dependents:
      - service: "user-service"
        operations: ["read", "write"]
      - service: "analytics-service"
        operations: ["read"]
    
    schema_dependencies:
      - table: "users"
        dependent_services: ["user-service", "order-service"]
        critical_columns: ["id", "email", "status"]
        notes: "emailカラム変更時はauth-serviceも影響"

# ======= 影響分析ルール =======
impact_rules:
  - trigger: "user-service.down"
    impacts:
      - component: "order-service"
        severity: "high"
        reason: "ユーザー認証できず注文不可"
        mitigation: "ゲスト注文機能で一時対応"
      
      - component: "admin-panel"
        severity: "medium"
        reason: "ユーザー情報表示不可"
        mitigation: "キャッシュデータで限定表示"

  - trigger: "user-db.schema_change"
    impacts:
      - component: "user-service"
        severity: "high"
        reason: "ORM定義要更新"
        action_required: "migration + code update"
      
      - component: "data-warehouse"
        severity: "medium"
        reason: "ETLジョブ要調整"
        action_required: "sync job update"

# ======= ライブラリ・パッケージ依存関係 =======
packages:
  critical:
    - name: "express"
      version: "4.18.2"
      reason: "メインフレームワーク"
      impact_if_updated: "全API影響の可能性"
      update_policy: "major version change requires approval"
    
    - name: "jsonwebtoken"
      version: "9.0.0"
      reason: "認証の要"
      security_critical: true
      impact_if_updated: "全認証システム影響"

  moderate:
    - name: "lodash"
      version: "4.17.21"
      reason: "ユーティリティ関数"
      impact_if_updated: "個別関数確認が必要"

# ======= 開発・デプロイ依存関係 =======
infrastructure:
  - name: "docker"
    version: "24.0.5"
    impact_if_unavailable: "開発・デプロイ停止"
    alternatives: ["podman"]
  
  - name: "kubernetes"
    version: "1.28"
    impact_if_unavailable: "プロダクション停止"
    critical_resources: ["ingress", "secrets", "configmaps"]

# ======= 変更時の注意事項 =======
change_procedures:
  database_schema:
    - "必ずmigrationファイル作成"
    - "staging環境で動作確認"
    - "dependent servicesの影響確認"
    - "rollback手順確認"
  
  api_changes:
    - "APIバージョニング確認"
    - "backward compatibility確認"
    - "クライアント側影響評価"
    - "段階的ロールアウト計画"

# ======= 緊急時連絡先 =======
contacts:
  user-service:
    primary: "@tanaka"
    secondary: "@suzuki"
    emergency: "#user-team-oncall"
  
  infrastructure:
    primary: "@yamada"
    secondary: "@sato"
    emergency: "#infra-team-oncall"
```

## サービス別詳細テンプレート

```yaml
# service-dependencies/user-service.yaml
service_name: "user-service"
last_updated: "2025-06-27"

# このサービスが依存しているもの
depends_on:
  databases:
    user_db:
      critical: true
      operations: ["read", "write", "migration"]
      fallback: "none"
      notes: "メインデータストア、停止時サービス完全停止"
  
  services:
    notification_service:
      critical: false
      operations: ["event_publish"]
      fallback: "queue events for retry"
      timeout: "5s"
      notes: "非同期処理、一時的な失敗は許容可能"
    
    auth_service:
      critical: true
      operations: ["token_validation"]
      fallback: "local cache (5min)"
      timeout: "3s"
      notes: "認証要、キャッシュで短時間の耐障害性確保"

# このサービスに依存しているもの  
depended_by:
  services:
    - name: "order-service"
      operations: ["user_lookup", "user_validation"]
      impact_when_down: "注文処理停止"
      mitigation: "ゲスト注文のみ継続"
    
    - name: "recommendation-service"
      operations: ["user_preferences"]
      impact_when_down: "パーソナライズ停止"
      mitigation: "汎用レコメンド表示"

# APIエンドポイント別影響
endpoints:
  "/api/users/{id}":
    dependencies: ["user_db"]
    impact_scope: "個別ユーザー操作"
    error_handling: "404 return"
  
  "/api/users":
    dependencies: ["user_db", "auth_service"]
    impact_scope: "ユーザー一覧表示"
    error_handling: "500 with retry instruction"

# 設定・環境変数依存
configuration:
  required_env_vars:
    - name: "DB_CONNECTION_STRING"
      impact_if_missing: "service起動不可"
    - name: "JWT_SECRET"
      impact_if_missing: "認証機能停止"
  
  feature_flags:
    - name: "ENABLE_EMAIL_VERIFICATION"
      dependent_services: ["notification_service"]
      impact_if_disabled: "メール認証スキップ"
```

## LLM指示用プロンプトテンプレート

```yaml
# llm-instructions.yaml - LLMに渡す指示書
instruction_context: |
  以下のYAMLファイルには、プロジェクトの依存関係情報が記載されています。
  この情報を基に、変更影響分析や質問回答を行ってください。

analysis_tasks:
  impact_analysis:
    prompt: |
      {service_name}を変更/停止した場合の影響を分析してください。
      dependencies.yamlの情報を参照し、以下の形式で回答してください：
      
      ## 直接影響 (Wave 1)
      - [影響先サービス]: [影響内容] - [深刻度: High/Medium/Low]
      
      ## 間接影響 (Wave 2)
      - [影響先サービス]: [影響内容] - [深刻度: High/Medium/Low]
      
      ## 推奨対応
      1. [即座に必要な対応]
      2. [中期的な対応]
      3. [予防策]

  dependency_check:
    prompt: |
      {change_description}を実施する前に確認すべき依存関係を教えてください。
      dependencies.yamlの情報を基に、チェックリスト形式で回答してください。

  rollback_plan:
    prompt: |
      {service_name}の変更をロールバックする際の手順を、
      依存関係を考慮して教えてください。
```

### 1. 初期セットアップ指示

```bash
# 1. プロジェクトルートにディレクトリ作成
mkdir -p docs/dependencies
cd docs/dependencies

# 2. メインファイル作成
cp dependencies-template.yaml dependencies.yaml

# 3. サービス別詳細ディレクトリ
mkdir service-dependencies
```

### 2. チームメンバーへの指示

**開発者向け指示:**

```markdown
## 依存関係ドキュメント更新ルール

### 新機能開発時
1. 新しい依存関係追加時は必ず `dependencies.yaml` を更新
2. サービス間の呼び出し追加時は `impact_rules` セクションも更新
3. PRに依存関係変更の説明を含める

### 修正手順
1. `docs/dependencies/dependencies.yaml` を編集
2. 変更理由をコミットメッセージに記載
3. 影響範囲をPR説明に明記

### 緊急時の確認方法
```bash
# 影響確認
grep -A 5 "service-name" docs/dependencies/dependencies.yaml

# 連絡先確認  
grep -A 3 "contacts:" docs/dependencies/dependencies.yaml
```

```
### 3. LLMとの連携指示

**ChatGPT/Claude向けプロンプト例:**
```

以下のYAMLファイルをプロジェクトの依存関係情報として読み込んでください。

[dependencies.yamlの内容をペースト]

今後このプロジェクトに関する質問をする際は、この依存関係情報を参照して回答してください。特に：

- サービス変更時の影響分析
- 障害時の対応手順
- デプロイ順序の決定
- セキュリティ更新の優先順位

で活用してください。

```
### 4. 運用のベストプラクティス

**定期メンテナンス:**
```yaml
maintenance_schedule:
  weekly:
    - "新規依存関係の確認・追加"
    - "削除された依存関係の除去"
  
  monthly:
    - "impact_rules の見直し"
    - "連絡先情報の更新"
  
  quarterly:
    - "テンプレート構造の見直し"
    - "チーム習熟度の確認"
```

**品質チェック:**

```bash
# YAMLファイルの構文チェック
yamllint docs/dependencies/dependencies.yaml

# 必須フィールドの存在確認
yq eval '.services[].name' docs/dependencies/dependencies.yaml

# 重複チェック
yq eval '.services[].name' docs/dependencies/dependencies.yaml | sort | uniq -d
```

このテンプレートを使って段階的に導入していけ。最初は基本情報だけ埋めて、徐々に詳細を追加していくのが成功の秘訣だ。
